#!/bin/bash
echo ""
echo ":::       ::: :::::::::: :::        ::::::::   ::::::::  ::::    ::::  :::::::::: "
echo ":+:       :+: :+:        :+:       :+:    :+: :+:    :+: +:+:+: :+:+:+ :+:        "
echo "+:+       +:+ +:+        +:+       +:+        +:+    +:+ +:+ +:+:+ +:+ +:+        "
echo "+#+  +:+  +#+ +#++:++#   +#+       +#+        +#+    +:+ +#+  +:+  +#+ +#++:++#   "
echo "+#+ +#+#+ +#+ +#+        +#+       +#+        +#+    +#+ +#+       +#+ +#+        "
echo " #+#+# #+#+#  #+#        #+#       #+#    #+# #+#    #+# #+#       #+# #+#        "
echo "  ###   ###   ########## ########## ########   ########  ###       ### ########## "
echo ""
echo "Do you want to update and Upgrade ? "
echo "Answer 1=yes and 2=no"
read Answer
if [ $Answer = 1 ]
then
sudo apt-get update 
sudo apt-get upgrade 
fi
echo "Do you want to creat a bin and curl repo in it ?"
echo "Answer 1=yes and 2=no"
read Answer
if [ $Answer = 1 ]
then
cd
mkdir bin
cd bin
curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo 
chmod a+x ~/bin/repo
fi 
echo "Do you want to setup Build Environment?"
echo "Answer 1=yes and 2=no"
read Answer
if [ $Answer = 1 ]
then
cd
cd bin/
sudo apt-get install bison build-essential curl ccache flex lib32ncurses5-dev lib32z1-dev libesd0-dev libncurses5-dev libsdl1.2-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev git-core make phablet-tools gperf openjdk-8-jdk -y
git clone https://github.com/akhilnarang/scripts.git build
cd build/setup/
bash android_build_env.sh
fi 
echo " Do you want to create PEX Folder ? "
echo "Answer 1=yes and 2=no"
read Answer
if [ $Answer = 1 ]
then
cd
cd bin/build
mkdir pex
fi 
echo "Do you want to create global Username & useremail ?"
echo "Answer 1=yes and 2=no"
read Answer
if [ $Answer = 1 ]
then
cd 
cd bin/build/pex
git config --global user.name "Samyak"
git config --global user.email "jainsamyak2002.sj@gmail.com"
fi
echo " Do you want to initialize PEX Repo ?"
echo "Answer 1=yes and 2=no"
read Answer
if [ $Answer = 1 ]
then  
cd 
cd bin/build/pex/
repo init -u https://github.com/PixelExtended/manifest -b eleven --depth=1
fi
echo "Do you want to sync Pex Source ?"
echo "Answer 1=yes and 2=no"
read Answer
if [ $Answer = 1 ]
then 
cd 
cd bin/build/pex/
repo sync -c -q --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
fi
echo "Do you want to clone device tree, kernel , vendor for mi a2 ?"
echo "Answer 1=yes and 2=no"
read Answer
if [ $Answer = 1 ]
then  
cd 
cd bin/build/pex/
git clone https://github.com/PixelExtended/device_xiaomi_jasmine_sprout.git device/xiaomi/jasmine_sprout
git clone https://github.com/PixelExtended/device_xiaomi_sdm660-common.git device/xiaomi/sdm660-common 
git clone https://github.com/xiaomi-sdm660/android_vendor_xiaomi_sdm660-common.git vendor/xiaomi/sdm660-common 
git clone https://github.com/xiaomi-sdm660/android_kernel_xiaomi_sdm660.git kernel/xiaomi/sdm660 
echo "Thankyou for using!! "
