#!/bin/bash
echo ""
echo ":::       ::: :::::::::: :::        ::::::::   ::::::::  ::::    ::::  :::::::::: "
echo ":+:       :+: :+:        :+:       :+:    :+: :+:    :+: +:+:+: :+:+:+ :+:        "
echo "+:+       +:+ +:+        +:+       +:+        +:+    +:+ +:+ +:+:+ +:+ +:+        "
echo "+#+  +:+  +#+ +#++:++#   +#+       +#+        +#+    +:+ +#+  +:+  +#+ +#++:++#   "
echo "+#+ +#+#+ +#+ +#+        +#+       +#+        +#+    +#+ +#+       +#+ +#+        "
echo " #+#+# #+#+#  #+#        #+#       #+#    #+# #+#    #+# #+#       #+# #+#        "
echo "  ###   ###   ########## ########## ########   ########  ###       ### ########## "
echo ""

echo "Do you want to creat a bin and curl repo in it ?"
echo "Answer 1=yes and 2=no"
read Answer
if [ $Answer = 1 ]
then
cd
mkdir bin
cd bin
curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo 
chmod a+x ~/bin/repo
fi

echo "Do you want to setup Build Environment?"
echo "Answer 1=yes and 2=no"
read Answer
if [ $Answer = 1 ]
then
git clone https://github.com/nparashar150/buildscript.git build_scripts
cd build_scripts/scripts/
bash clone_build.sh
fi
